### ISSUE TITLE
Is there any way to see the full curl command that was used?

### ISSUE THREAD

**Issue by Jesse-Millwood** [alphapapa/plz.el#11]
Is there a way to see the whole curl command and arguments that were sent? 

I'm trying to interact with the Gitlab REST API and I keep getting unauthorized responses. The API requires a `PRIVATE-TOKEN` header and I give it like this: 

```
(defun gl-plz-issues ()
  (interactive)
  (let* ((gl-buffer-name "*Gitlab*")
         (gl-buffer (get-buffer-create gl-buffer-name))
         (issues-url (concat gl-url-base "/issues")))
    (with-current-buffer gl-buffer
      (insert "From Plz _______________________________________\n")
      (plz 'get issues-url
        :headers '(("PRIVATE-TOKEN" . gl-personal-access-token))
        :as 'buffer))
    (insert "\n\n-----------------------------------------------\n")))
```

I must be using `plz` wrong because the following does work: 

```
(defun gl-curl-issues ()
  (interactive)
  (let* ((gl-buffer-name "*Gitlab*")
         (gl-buffer (get-buffer-create gl-buffer-name))
         (curl-url (concat gl-url-base "/issues"))
    (with-current-buffer gl-buffer
      (insert "From CURL _______________________________\n")
      (call-process "curl" nil t nil
                    "--header" (format "PRIVATE-TOKEN: %s" gl-personal-access-token)
                    curl-url)
      (insert "\n_________________________________________\n\n"))))
```

Fwiw, I was getting a similar issue with `request.el`. So it's probably on me but I can't pin point it without seeing what the actual curl command is.

**Comment by alphapapa** [comment]
You could use Edebug and step through the code in the `plz` function to see the value of various variables, e.g. https://github.com/alphapapa/plz.el/blob/80aeae0d201b06088d4b7543a603d97bdbccb948/plz.el#L351

But in your code, the problem appears to be that you're passing `'(("PRIVATE-TOKEN" . gl-personal-access-token))` as the `:headers`, which is not a backquoted-and-spliced list, so you're essentially passing the string `"gl-personal-access-token"` rather than the access token stored in that variable.

**Comment by Jesse-Millwood** [comment]
Awesome, that worked! 
Thanks!

**Comment by alphapapa** [comment]
You're welcome.

BTW, FYI, if you use `(plz ... :as 'buffer)`, it will return the response buffer as the value; it's not like using `call-process`.  That should be in the documentation.
