### ISSUE TITLE
Newlines are stripped in POST requests

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/plz.el#13]
I notice that there are no newlines in the response to the following request:

```
(plz 'post "https://httpbin.org/post"
  :headers '(("Content-Type" . "text/plain"))
  :body "hello
world"
  :as #'json-read
  :then (lambda (alist)
          (message "Result: %s" (alist-get 'data alist))))
```

Expected:
`hello\nworld`

Actual:
`helloworld`

Am I doing something wrong?

**Comment by alphapapa** [comment]
IIUC newlines are not allowed in JSON values, so this would seem to be an issue with the use of the JSON format rather than this library.  IOW, if you sent the same request to httpbin.org with any client and then parse the JSON response, you should see the same behavior.  Alternatively, you might look at the Emacs `json` library and see if there are options to control how newlines are parsed in values.

**Comment by josephmturner** [comment]
Thank you!!! You're right, I need to encode the JSON first:

```
(plz 'post "https://httpbin.org/post"
  :headers '(("Content-Type" . "text/plain"))
  :body (json-encode "hello
world")
  :as #'json-read
  :then (lambda (alist)
          (message "Result: %s" (alist-get 'data alist))))
```

**Comment by alphapapa** [comment]
Note as well that you're sending `text/plain` as the content-type while you're actually sending JSON.

**Comment by josephmturner** [comment]
Yes, good catch. Thank you!
