### ISSUE TITLE
Support empty `POST` requests

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/plz.el#16]
Would you support sending `POST` requests with no body?

**Comment by alphapapa** [comment]
If that's needed, sure, why not.  :)

**Comment by josephmturner** [comment]
It's not that important. I have a use-case for sending a `POST` request with no body, and
```
(plz 'post url
  :as 'response)
```
looks cleaner than
```
(plz 'post url
  :body ""
  :as 'response)
```
If allowing empty `POST` requests adds unnecessary complexity to `plz.el`, let's not do it.

**Comment by alphapapa** [comment]
Well, it's mostly a matter of deleting one line of code, an assertion that signals an error if the body is not specified, and then specifying a default empty string for the body.  So it's not a big deal on the code side.

My concern is about making the API clear for the user.  I added the assertion because it seems like it would generally be an oversight if the user made a POST or PUT request without a body, and signaling the error before sending the request seems more helpful than making the request and having the user potentially be confused by the response from the server.

I don't have strong feelings about this either way.  I suppose I'd default to the status quo and letting the user give the empty string argument.  

What do you think?  Thanks.

**Comment by Dima-369** [comment]
> What do you think?

I also have use-cases for using methods like `POST` and `PUT` without a request body and I would highly prefer this:

```emacs-lisp
(plz 'post url
  :as 'response)
```

> and signaling the error before sending the request seems more helpful than making the request and having the user potentially be confused by the response from the server.

Well, you can turn this argument either way.
Adding `:body ""` confuses me more (but once you know this, it's kind of fine) because it is not required for `'get` or the others.

**Comment by alphapapa** [comment]
@Dima-369 Ok, that's good enough for me to make this change.  Thanks for your feedback.

**Comment by josephmturner** [comment]
Thank you!
