### ISSUE TITLE
Prompts to kill buffer with running process

### ISSUE THREAD

**Issue by Dima-369** [alphapapa/plz.el#30]
_On a larger queue with around 65 URLs and :limit 6, I often see: "Buffer " *plz-request-curl*-143946" has a running process" prompts?_

I see those on Emacs 30.0.50. Is this related to https://github.com/alphapapa/plz.el/issues/28?

Since they are quite annoying because the minibuffer prompts one about them.

If I use a smaller limit or less URLs, I think it doesn't happen as often, if ever.

**Comment by alphapapa** [comment]
I've sometimes seen this happen in hyperdrive.el, which uses plz.el as a backend.  I've tried various things to fix it, including simple things like checking `process-live-p` before calling `kill-buffer`.  But it seems like it shouldn't be happening in the first place, because the sentinel shouldn't be getting called while the process is still running, AFAICT.

Anyway, there's a WIP branch that makes some more significant changes in the sentinel and error handling that will be released in the future.  It solves various problems; it might help this one too.  Feel free to try it: https://github.com/alphapapa/plz.el/tree/wip/no-signal-from-sentinel

**Comment by Dima-369** [comment]
> Also, are you saying that you only see this behavior on Emacs master? Please note that Emacs 29 hasn't even been released yet, so your testing on Emacs 30, while it could be helpful in the long run, could also be misleading, especially if you don't perform the same testing with an actually released version of Emacs.

Ah no, I don't. I am just using Emacs `master` as a daily driver. 

And since you mentioned it, on what version of Emacs do you see the same issue?

**Comment by alphapapa** [comment]
> And since you mentioned it, on what version of Emacs do you see the same issue?

In that case, it was on Emacs 27.1 on Debian 11.

**Comment by alphapapa** [comment]
This should be fixed in v0.7.
