### ISSUE TITLE
Interactive version

### ISSUE THREAD

**Issue by astoff** [alphapapa/plz.el#40]
I'm using an interactive version of plz which I might eventually make into a package, so I thought it's reasonable to ask what you think — in particular about the name [plzi](https://github.com/astoff/plzi.el).

It's a basically a function with the same API as plz, but displaying the response nicely rendered in a buffer. It's meant as an alternative to packages such as verb and restclient for those who prefer to write elisp instead of the ad-hoc syntax of those existing packages.

**Comment by alphapapa** [comment]
Hi Augusto,

Thanks, this is interesting.  The code looks good.

As for the name...what a question.  I'm not sure I'm the best person to ask.  :)  I got some flak for the name `plz` when I submitted the package to GNU ELPA.  And I've argued for using more descriptive names when I've reviewed package submissions to ELPA and MELPA.  But in the end, "Naming things is hard," one of the "two hard problems."

So, trying to put on my "impartial hat," I'd suggest trying to discover a more descriptive, pronounceable name.  If nothing else, the name `plzi` is so visually close to `plz` that it might be confusing to users who don't know what either one is.

I'd also suggest that you consider contributing this functionality to one of those other packages, if it seems feasible.  Maybe they could have an add-on package or an alternative interaction mode that would use `plz` as a backend.  Generally it's preferable to extend existing tools rather than making new ones, but it's always a judgment call.

Here's a silly name suggestion I just thought of: `httplz`.  :)  At least it's longer, and it communicates that it's to do with HTTP.  (And if you use that, people will wonder why I didn't use that name instead of `plz`...oh well.)

Another silly suggestion: `plz-see` (as in, using `plz` to "see" the HTTP request and response, as well as a joke on the common documentation phrase, "please see..."  I actually think this one might be a good name, so if you do decide to publish it separately, I'd recommend using this name.  (In fact, it would potentially help with debugging apps that use `plz` as a backend, if the developer could just replace `plz` with `plz-see` and have a request pop up in a buffer with the response, perhaps also handling the request normally.)

Let me know what you think.  Thanks.

**Comment by astoff** [comment]
I like `plz-see`! I guess this didn't cross my mind because I always read „Postleitzahl“ rather than what you meant — the only valid flak here, in my opinion. (By the way, I thought the logical name choice would have been curly...)

> In fact, it would potentially help with debugging apps that use plz as a backend

True, and this is the reason why I don't think it makes so much sense to try integrating with those other rest clients. I'm more interested in writing my test requests in Elisp than in changing / improving the backend.

Anyway, I will keep using and extending this for a while before submitting to ELPA. I'll close this non-issue, but I'm happy to continue discussing.

**Comment by alphapapa** [comment]
> I like `plz-see`! I guess this didn't cross my mind because I always read „Postleitzahl“ rather than what you meant — the only valid flak here, in my opinion. 

Yeah, someone mentioned that reference on emacs-devel (was it you?  I forget...).  I wasn't even aware of it until then.

> (By the way, I thought the logical name choice would have been curly...)

Yeah, I considered that at one time, it's even in the notes file: https://github.com/alphapapa/plz.el/blob/meta/notes/NOTES.org#name  I think I went with `plz` because it's shorter, and because it doesn't mention the backend implementation in the code (not that I intend to change it, but if I did...).
> 
> > In fact, it would potentially help with debugging apps that use plz as a backend
> 
> True, and this is the reason why I don't think it makes so much sense to try integrating with those other rest clients. I'm more interested in writing my test requests in Elisp than in changing / improving the backend.
> 
> Anyway, I will keep using and extending this for a while before submitting to ELPA. I'll close this non-issue, but I'm happy to continue discussing.

Sounds good.  Thanks for letting me know.  I look forward to seeing `plz-see`'s progress.  :)
